<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup Label="Host">
		<PackageVersion Include="Asp.Versioning.OData" Version="8.2.1" />
		<PackageVersion Include="Asp.Versioning.OData.ApiExplorer" Version="8.2.1" />
		<PackageVersion Include="Aspire.Hosting.AppHost" Version="13.4.2" />
		<PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.4.2" />
		<PackageVersion Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
		<PackageVersion Include="Microsoft.Extensions.Compliance.Redaction" Version="10.6.0" />
		<PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
		<PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0" />
		<PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.6.0" />
		<PackageVersion Include="NSwag.AspNetCore" Version="14.7.1" />
		<PackageVersion Include="NSwag.MSBuild" Version="14.7.1" />
		<PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
		<PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
		<PackageVersion Include="WolverineFx" Version="6.5.1" />
		<PackageVersion Include="WolverineFx.Marten" Version="6.5.1" />
	</ItemGroup>
	<ItemGroup Label="Testing">
		<PackageVersion Include="Aspire.Hosting.Testing" Version="13.4.2" />
		<PackageVersion Include="coverlet.collector" Version="10.0.1" />
		<PackageVersion Include="FSharp.Core" Version="10.1.300" />
		<PackageVersion Include="JunitXml.TestLogger" Version="8.0.0" />
		<PackageVersion Include="LimeFlight.OpenAPI.Diff" Version="3.0.10-preview.8" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
		<PackageVersion Include="xunit" Version="2.9.3" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>
</Project>