<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<GenerateProgramFile>false</GenerateProgramFile>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="PrivacyRedactionTests.fs" />
		<Compile Include="DIInjectionExampleTests.fs" />
		<Compile Include="Program.fs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="FSharp.Core" />
		<PackageReference Include="JunitXml.TestLogger" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Excos.Platform.Common\Excos.Platform.Common.csproj" />
	  <ProjectReference Include="..\Excos.Platform.TestingUtilities\Excos.Platform.TestingUtilities.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>

</Project>
