name: Bug Report
description: Create a report to help us improve
labels: []
body:
  - type: markdown
    attributes:
      value: |
        We welcome bug reports! This template will help us gather the information we need to start the triage process.
        Before submitting a bug report, please use the search functionality to see if a similar bug has been reported already.
  - type: input
    id: version
    attributes:
      label: Code version
      description: Please provide which version you're using (SHA if git based)
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please share a clear and concise description of the problem.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
      placeholder: Minimal Reproduction
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages, exception stacktraces or memory dumps.
      placeholder: Actual behavior
    validations:
      required: true
  - type: textarea
    id: known-workarounds
    attributes:
      label: Known Workarounds
      description: |
        Please provide a description of any known workarounds.
      placeholder: Known Workarounds
    validations:
      required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Additional information
      description: |
        If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
      placeholder: Additional information
    validations:
      required: false