# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Install .NET Aspire workload
      run: dotnet workload install aspire
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        if [ "${{ runner.debug }}" = "1" ]; then
          dotnet build --no-restore /bl:msbuild.binlog
        else
          dotnet build --no-restore
        fi
    - name: Upload msbuild.binlog
      if: runner.debug == '1' && always()
      uses: actions/upload-artifact@v4
      with:
        name: msbuild-binlog
        path: msbuild.binlog
    - name: Test
      run: ./scripts/trace-watcher Excos.Platform.WebApiHost & dotnet test --no-build --verbosity normal --logger:"junit;LogFilePath=dotnet-test-result.xml"
    - name: Upload trace
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trace
        path: "*trace.json"
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "**/dotnet-test-result.xml"
      if: success() || failure()
