name: Add PR size label

on: 
  pull_request:

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          xs_label: 'size:XS'
          xs_max_size: '25'
          s_label: 'size:S'
          s_max_size: '150'
          m_label: 'size:M'
          m_max_size: '500'
          l_label: 'size:L'
          l_max_size: '1200'
          xl_label: 'size:XL'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1200 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          ignore_file_deletions: true
        env:
          BASHOPTS: xtrace
